# Generated by Django 3.0.3 on 2020-02-29 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HozRequest', '0002_auto_20200229_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(default='user', on_delete=django.db.models.deletion.DO_NOTHING, to='HozRequest.User'),
        ),
    ]
