# Generated by Django 3.0.3 on 2020-03-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HozRequest', '0003_auto_20200229_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='photo',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
