# Generated by Django 3.0.3 on 2020-03-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HozRequest', '0005_auto_20200301_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='photo_url',
            field=models.CharField(max_length=200),
        ),
    ]
